# Generated by Django 3.1.4 on 2020-12-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductionTask',
            new_name='Production_Task',
        ),
    ]
