# Generated by Django 3.1.4 on 2020-12-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0002_auto_20201221_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_task',
            name='demand_allocation_method',
            field=models.CharField(choices=[('soft', 'Свободное'), ('hard', 'Равномерное')], default='soft', max_length=20),
        ),
        migrations.AddField(
            model_name='production_task',
            name='demand_calculate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='production_task',
            name='demand_data_source',
            field=models.CharField(choices=[('scheduler', 'Планировщик'), ('statistical_data', 'Статистика')], default='scheduler', max_length=20),
        ),
        migrations.AddField(
            model_name='production_task',
            name='work_scope_measure',
            field=models.CharField(choices=[('minutes', 'Минуты'), ('pieces', 'Штуки'), ('persons_number', 'Кол-во человек')], default='minutes', max_length=20),
        ),
    ]
