# Generated by Django 3.1.4 on 2020-12-22 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0005_auto_20201222_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='subdivision_id',
            new_name='subdivision',
        ),
        migrations.RenameField(
            model_name='subdivision',
            old_name='organization_id',
            new_name='organization',
        ),
    ]
