# Generated by Django 3.1.4 on 2020-12-22 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0006_auto_20201222_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
				('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wfm.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('subdivision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wfm.subdivision')),
            ],
        ),
    ]
