# Generated by Django 3.1.4 on 2020-12-23 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0007_department_name1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production_task',
            name='demand_allocation_method',
            field=models.CharField(choices=[('soft', 'Свободное'), ('inseparable', 'Неразрывный'), ('hard', 'Равномерное')], default='soft', max_length=20),
        ),
        migrations.AlterField(
            model_name='production_task',
            name='work_scope_measure',
            field=models.CharField(choices=[('minutes', 'Минуты'), ('pieces', 'Штуки')], default='minutes', max_length=20),
        ),
    ]
