# Generated by Django 3.1.4 on 2020-12-24 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0010_auto_20201224_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_set', to='wfm.subdivision'),
        ),
        migrations.AlterField(
            model_name='production_task',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_set', to='wfm.organization'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivision_set', to='wfm.organization'),
        ),
    ]
