# Generated by Django 3.1.4 on 2020-12-28 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0012_scheduled_production_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_set', to='wfm.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks_In_Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=0)),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_in_duty_set', to='wfm.job_duty')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_in_duty_set', to='wfm.production_task')),
            ],
        ),
    ]
