# Generated by Django 3.1.4 on 2021-01-12 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0013_job_duty_tasks_in_duty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_position_set', to='wfm.organization')),
            ],
        ),
    ]
