# Generated by Django 3.1.4 on 2021-01-13 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wfm', '0014_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=30)),
                ('personnel_number', models.CharField(max_length=30)),
                ('duties', models.ManyToManyField(to='wfm.Job_Duty')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_position_set', to='wfm.employee_position')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_set', to='wfm.subdivision')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
