# Generated by Django 3.1.4 on 2021-01-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0015_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='part_time_job_org',
            field=models.ManyToManyField(to='wfm.Organization'),
        ),
    ]
