# Generated by Django 3.1.4 on 2020-12-24 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfm', '0009_auto_20201223_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production_task',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfm.organization'),
        ),
    ]
